#LETRAS
TAMANNO_LETRA = 20
TAMANNO_LETRA_GRANDE = 80
TAMAÑO_LETRA_SEPARADA = 40

#TIEMPO / FOTOGRAMAS
FPS_inicial = 60
TIEMPO_MAX = 60

#CONFIG PANTALLA / COLORES
ANCHO = 1280
ALTO = 720
COLOR_LETRAS = (255, 255, 255)
COLOR_FONDO = (255, 255, 255)
COLOR_TEXTO = (200,200,200)
COLOR_TIEMPO_FINAL = (200,20,10)
COLOR_PALABRA_ANTERIOR = (255, 0, 255)

#PUNTAJES
PUNTAJE_MAXIMO = 5
PUNTAJE_MEDIO = 3
PUNTAJE_MINIMO = 2

#RECURSOS
SONIDO_VERDADERO = 'recursos/sonidos/audio_correcto.wav'
SONIDO_FALSO = 'recursos/sonidos/audio_incorrecto.wav'
IMAGEN_FONDO = 'recursos/imagenes/fondo_escalon.png'
IMAGEN_ICONO = 'recursos/imagenes/esc.png'